-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "movies" (
	"title" varchar NOT NULL,
	"description" text,
	"release_date" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"language" varchar,
	"runtime" numeric,
	"image_url" text,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"boost" boolean DEFAULT false,
	"director" varchar
);
-- statement-breakpoint
ALTER TABLE "movies" ENABLE ROW LEVEL SECURITY;-- statement-breakpoint
CREATE TABLE "countries" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" varchar NOT NULL,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "countries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text,
	CONSTRAINT "countries_name_key" UNIQUE("name")
);
-- statement-breakpoint
ALTER TABLE "countries" ENABLE ROW LEVEL SECURITY;-- statement-breakpoint
CREATE TABLE "keywords" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "keywords_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" varchar
);
-- statement-breakpoint
ALTER TABLE "keywords" ENABLE ROW LEVEL SECURITY;-- statement-breakpoint
CREATE TABLE "directors" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" varchar,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "directors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	CONSTRAINT "directors_id_key" UNIQUE("id")
);
-- statement-breakpoint
ALTER TABLE "directors" ENABLE ROW LEVEL SECURITY;-- statement-breakpoint
CREATE TABLE "genres" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" varchar,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "genres_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	CONSTRAINT "genres_name_key" UNIQUE("name")
);
-- statement-breakpoint
ALTER TABLE "genres" ENABLE ROW LEVEL SECURITY;-- statement-breakpoint
CREATE TABLE "movie_genres" (
	"movie_id" uuid NOT NULL,
	"genre_id" bigint NOT NULL,
	CONSTRAINT "movie_genres_pkey" PRIMARY KEY("movie_id","genre_id")
);
-- statement-breakpoint
ALTER TABLE "movie_genres" ENABLE ROW LEVEL SECURITY;-- statement-breakpoint
CREATE TABLE "movie_keywords" (
	"movie_id" uuid NOT NULL,
	"keyword_id" integer NOT NULL,
	CONSTRAINT "movie_keywords_pkey" PRIMARY KEY("movie_id","keyword_id")
);
-- statement-breakpoint
ALTER TABLE "movie_keywords" ENABLE ROW LEVEL SECURITY;-- statement-breakpoint
CREATE TABLE "movie_countries" (
	"movie_id" uuid NOT NULL,
	"country_id" bigint NOT NULL,
	CONSTRAINT "movie_countries_pkey" PRIMARY KEY("movie_id","country_id")
);
-- statement-breakpoint
ALTER TABLE "movie_countries" ENABLE ROW LEVEL SECURITY;-- statement-breakpoint
CREATE TABLE "movie_directors" (
	"movie_id" uuid NOT NULL,
	"director_id" bigint NOT NULL,
	CONSTRAINT "movie_directors_pkey" PRIMARY KEY("movie_id","director_id")
);
-- statement-breakpoint
ALTER TABLE "movie_directors" ENABLE ROW LEVEL SECURITY;-- statement-breakpoint
ALTER TABLE "movie_genres" ADD CONSTRAINT "movie_genres_genre_id_fkey" FOREIGN KEY ("genre_id") REFERENCES "public"."genres"("id") ON DELETE cascade ON UPDATE no action;-- statement-breakpoint
ALTER TABLE "movie_genres" ADD CONSTRAINT "movie_genres_movie_id_fkey" FOREIGN KEY ("movie_id") REFERENCES "public"."movies"("id") ON DELETE cascade ON UPDATE no action;-- statement-breakpoint
ALTER TABLE "movie_keywords" ADD CONSTRAINT "movie_keywords_keyword_id_fkey" FOREIGN KEY ("keyword_id") REFERENCES "public"."keywords"("id") ON DELETE cascade ON UPDATE no action;-- statement-breakpoint
ALTER TABLE "movie_keywords" ADD CONSTRAINT "movie_keywords_movie_id_fkey" FOREIGN KEY ("movie_id") REFERENCES "public"."movies"("id") ON DELETE cascade ON UPDATE no action;-- statement-breakpoint
ALTER TABLE "movie_countries" ADD CONSTRAINT "movie_countries_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "public"."countries"("id") ON DELETE cascade ON UPDATE no action;-- statement-breakpoint
ALTER TABLE "movie_countries" ADD CONSTRAINT "movie_countries_movie_id_fkey" FOREIGN KEY ("movie_id") REFERENCES "public"."movies"("id") ON DELETE cascade ON UPDATE no action;-- statement-breakpoint
ALTER TABLE "movie_directors" ADD CONSTRAINT "movie_directors_director_id_fkey" FOREIGN KEY ("director_id") REFERENCES "public"."directors"("id") ON DELETE cascade ON UPDATE no action;-- statement-breakpoint
ALTER TABLE "movie_directors" ADD CONSTRAINT "movie_directors_movie_id_fkey" FOREIGN KEY ("movie_id") REFERENCES "public"."movies"("id") ON DELETE cascade ON UPDATE no action;-- statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "movies" AS PERMISSIVE FOR SELECT TO public USING (true);-- statement-breakpoint
CREATE POLICY "Enable insert for all users" ON "movies" AS PERMISSIVE FOR INSERT TO public;-- statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "countries" AS PERMISSIVE FOR SELECT TO public USING (true);-- statement-breakpoint
CREATE POLICY "Enable insert for all users" ON "countries" AS PERMISSIVE FOR INSERT TO public;-- statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "keywords" AS PERMISSIVE FOR SELECT TO public USING (true);-- statement-breakpoint
CREATE POLICY "Enable insert for all users" ON "keywords" AS PERMISSIVE FOR INSERT TO public;-- statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "directors" AS PERMISSIVE FOR SELECT TO public USING (true);-- statement-breakpoint
CREATE POLICY "Enable insert for all users" ON "directors" AS PERMISSIVE FOR INSERT TO public;-- statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "genres" AS PERMISSIVE FOR SELECT TO public USING (true);-- statement-breakpoint
CREATE POLICY "Enable insert for all users" ON "genres" AS PERMISSIVE FOR INSERT TO public;-- statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "movie_genres" AS PERMISSIVE FOR SELECT TO public USING (true);-- statement-breakpoint
CREATE POLICY "Enable insert for all users" ON "movie_genres" AS PERMISSIVE FOR INSERT TO public;-- statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "movie_keywords" AS PERMISSIVE FOR SELECT TO public USING (true);-- statement-breakpoint
CREATE POLICY "Enable insert for all users" ON "movie_keywords" AS PERMISSIVE FOR INSERT TO public;-- statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "movie_countries" AS PERMISSIVE FOR SELECT TO public USING (true);-- statement-breakpoint
CREATE POLICY "Enable insert for all users" ON "movie_countries" AS PERMISSIVE FOR INSERT TO public;-- statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "movie_directors" AS PERMISSIVE FOR SELECT TO public USING (true);-- statement-breakpoint
CREATE POLICY "Enable insert for all users" ON "movie_directors" AS PERMISSIVE FOR INSERT TO public;
*/